### ISSUE TITLE
Calling query_once() multiple times causes duplicates to accumulate

### ISSUE THREAD

**Issue by mirko** [cbrand/micropython-mdns#11]
I'm calling `query_once()` every n seconds in a loop and noticed, that over time the list grows, starting containing duplicates.
This happens until, in my case on esp32, the process crashes, causing a reset.

**Comment by cbrand** [comment]
Thank you for the report.

I checked the corresponding source code and do have a follow up question:
1. Did you before calling `query_once` run the "protocol, service" calling `query`? That seems to be the only way this can accumulate if I read the code correctly.
2. The returned list in `query_once` returns duplicates. Currently in the background there is a dictionary which hashes the DNS responses coming from the wire and do only use `port` and `target` as the dictionary hash generation. So could you double check if the `port` changes in the DNS responses?

**Comment by cbrand** [comment]
Closing this as I did not hear anything back. If you still run into the issue feel free to comment and I reopen it.
