### ISSUE TITLE
Can i use it without pip?

### ISSUE THREAD

**Issue by DUYA112233** [cbrand/micropython-mdns#22]
Sorry, this may be a silly question. I am a beginner in micropython and I am using a development board customized based on micropython1.12 without upip or mip. Can I use the source code to call this library?

**Comment by cbrand** [comment]
Hey yes mostly you need to embed it into the kernel configuration anyhow as you need to disable the boards native mdns support.

In theory you could just take the code from the micropython_mdns folder and copy it into your source directory. As long as native mdns is disabled you'll be able to import and run the code as it would be with mip or upip.

**Comment by cbrand** [comment]
Sorry to be precise you need the folder `mdns_client` from:

https://github.com/cbrand/micropython-mdns/tree/main/src

That is all you need to copy onto your board to have the complete functionality.
