### ISSUE TITLE
Firmware not Flashing on Pico W

### ISSUE THREAD

**Issue by maxacode** [cbrand/micropython-mdns#26]
The available firmware "firmware.mp.1.23 or 22.rp2.uf2" is not being flashed on the Pico W. 

When copying it over, it does not reboot like other ones. Even with manual reboot the new Firmware does not get flashed. 

I even compiled a new one with provided docker config but those do not work either. 

Output seems correct. 

![image](https://github.com/user-attachments/assets/63923ae3-9a13-4bd2-b879-2b4177756b92)

**Comment by maxacode** [comment]
Also the output file size (857KB) seems to small compared to the official MP size of 1.7MB

**Comment by cbrand** [comment]
Hey thanks for opening it. I sadly do not have a Pico W there and am happy that someone now actually tested it.

See https://github.com/cbrand/micropython-mdns/issues/9#issuecomment-1925869228 for what I tried to do. Weird that it build though and it does not work at all then.

After checking your issue I found https://forum.micropython.org/viewtopic.php?t=9965 and I updated the Dockerfile accordingly. Could you double check if it works now with the updated Dockerfile and get back to me?

**Comment by cbrand** [comment]
Thanks for double checking and the offer! I guess it is faster for me to order one to test it out once on my end. I should have some time on the weekend to take a look and hopefully get back to you with a positive result then :) Sorry for the inconvenience.

**Comment by cbrand** [comment]
Alright I got a test Pico W and the problem was to copy the wrong file even though it built correctly -.- I updated in the release the files feel free to download it and test it.

For me the new files work now. Can you double check on your side and close the issue if it is fine?

**Comment by cbrand** [comment]
Going to close this for now. Feel free to reopen it if it does not work on your end.
