### ISSUE TITLE
How to compile / build into micropython binary / firmware file as frozen module

### ISSUE THREAD

**Issue by mirko** [cbrand/micropython-mdns#8]
I'm trying to bake this project into my firmware image as frozen module but somehow fail.
Adding cloned and checked out git repo to a port's/board's manifest file like this:
`freeze("$(MPY_DIR)/lib/mdns/src/mdns_client")`
does successfully freeze and compile respective files in.
However - at least on the UNIX port - importing does not work:
```
>>> import service_discovery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "service_discovery/__init__.py", line 3, in <module>
  File "service_discovery/discovery.py", line 6, in <module>
ImportError: can't perform relative import
```
Probably I'm overlooking something obvious.
Worst case is that the 'from ..X import Y`-syntax simply doesn't work when compiled in as frozen module.

If it's supposed to work, I guess a quick note on how to embed this software as frozen-module in the docs/README might be a good idea.

**Comment by cbrand** [comment]
Hm i did not encounter this use case yet. In general I think absoluteifying the imports would fix this and is a better way of handling these imports anyhow.
Let me remove the relative imports and then I would appreciate it if you can do a retest.

**Comment by cbrand** [comment]
@mirko can you try with the most recent main branch again?

**Comment by mirko** [comment]
Looking better, but failing otherwise now.

Embedding it via
`package("mdns_client", base_path="$(MPY_DIR)/lib/mdns/src")` (in my case)
results in
```
MPY mdns_client/util.py
MPY mdns_client/responder.py
MPY mdns_client/constants.py
MPY mdns_client/__init__.py
MPY mdns_client/parser.py
MPY mdns_client/structs.py
MPY mdns_client/client.py
MPY mdns_client/service_discovery/txt_discovery.py
MPY mdns_client/service_discovery/__init__.py
MPY mdns_client/service_discovery/discovery.py
MPY mdns_client/service_discovery/service_response.py
MPY mdns_client/service_discovery/service_monitor.py
GEN build-indielux/frozen_content.c
CC build-indielux/frozen_content.c
```
However importing the package or from then package, e.g.
`from mdns_client import service_discovery`
results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mdns_client/__init__.py", line 3, in <module>
  File "mdns_client/client.py", line 5, in <module>
ImportError: can't import name select
```
And now I wonder whether `select` not being available might be a port-specific thing(?)

**Comment by mirko** [comment]
Hm, I'm having the "(u)select"-module available:
```
>>> import select
>>> dir(select)
['__class__', '__name__', '__dict__', 'POLLERR', 'POLLHUP', 'POLLIN', 'POLLOUT', 'poll']
>>> 
```
However that doesn't provide a select function, as used in https://github.com/cbrand/micropython-mdns/blob/main/src/mdns_client/client.py#L99

**Comment by mirko** [comment]
I'm on the UNIX port, however there's a couple of other things preventing this implementation from working there.
E.g. `IPPROTO_IP` and `IP_ADD_MEMBERSHIP` aren't exposed for the port's usocket-variant (as it isn't for most ports AFAIS).
I didn't continue, but I think it's fair to say, that currently only the esp32 port is supported.

**Comment by cbrand** [comment]
The unix port is actually a pretty down-stripped version when it comes to network communication and debugging.

Any microcontroller port does have this functionality included but yes the unix port sadly is in this instance not suitable.

**Comment by mirko** [comment]
From grepping for `IPPROTO_IP` it *is* listed as part of the generic `extmod/modusocket.c`, *however* the lines in question are commented out: https://github.com/micropython/micropython/blob/master/extmod/modusocket.c#L638
`IPPROTO_IP` is actually defined  in `ports/esp32/modsocket.c`, hence my understanding that it's only available for esp32.

PS: Simply commenting-in respective lines doesn't cut it :)
